package PCNMClient.PCNMClientView;

/**
 * This class implements PC-Components search screen
 * @author ori ziv
 */
public class PCCompSCR extends javax.swing.JPanel {

    /**
     * Creates new form PCCompSCR
     */
    public PCCompSCR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScreenTitle = new javax.swing.JLabel();
        lblSearchTitle = new javax.swing.JLabel();
        lblNoFilter = new javax.swing.JLabel();
        lblSearchName = new javax.swing.JLabel();
        lblSearchDescription = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(630, 600));

        lblScreenTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblScreenTitle.setForeground(java.awt.Color.red);
        lblScreenTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScreenTitle.setText("PC Components Management");
        lblScreenTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblScreenTitle.setName("lblScreenTitle"); // NOI18N

        lblSearchTitle.setBackground(java.awt.Color.white);
        lblSearchTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblSearchTitle.setForeground(java.awt.Color.red);
        lblSearchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchTitle.setText("Search For PC Components");

        lblNoFilter.setBackground(java.awt.Color.white);
        lblNoFilter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNoFilter.setForeground(java.awt.Color.red);
        lblNoFilter.setText("Leave text fields empty for all PC Components");

        lblSearchName.setBackground(java.awt.Color.white);
        lblSearchName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearchName.setText("Search by Component name:");

        lblSearchDescription.setBackground(java.awt.Color.white);
        lblSearchDescription.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearchDescription.setText("Search by Component Description:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblScreenTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addComponent(lblSearchTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNoFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearchName)
                    .addComponent(lblSearchDescription))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScreenTitle)
                .addGap(18, 18, 18)
                .addComponent(lblSearchTitle)
                .addGap(18, 18, 18)
                .addComponent(lblNoFilter)
                .addGap(18, 18, 18)
                .addComponent(lblSearchName)
                .addGap(18, 18, 18)
                .addComponent(lblSearchDescription)
                .addContainerGap(346, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNoFilter;
    private javax.swing.JLabel lblScreenTitle;
    private javax.swing.JLabel lblSearchDescription;
    private javax.swing.JLabel lblSearchName;
    private javax.swing.JLabel lblSearchTitle;
    // End of variables declaration//GEN-END:variables
}
