package PCNMClient.PCNMClientView;

import java.util.ArrayList;

/**
 * This class implements the PC search results screen
 * @author ori ziv
 */
public class PCSearchResultSCR extends javax.swing.JPanel {

    /**
     * Creates new form PCSearchResultSCR
     */
    public PCSearchResultSCR() {
        initComponents();
    }

    /**
     * This constructor utilise the default constructor and then loads content into the screen's forms
     * @param pc_tbl 
     */
    public PCSearchResultSCR(ArrayList<String> pc_tbl) {
        this();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
