package PCNMClient.PCNMClientView;

import PCNMClient.PCNMClientController.WorkstationCTRL;
import PCNMClient.PCNMClientStart;
import static PCNMClient.PCNMClientView.WindowMustHave.showDialog;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ori ziv
 */
public class WorkstationSCR extends javax.swing.JPanel {
    private ArrayList<String[]> types;
    private ArrayList<String> ws_tbl;
    private int rowCounter;
    private boolean[] rowsToShow;
    private String[][] tableContent;
    private FormFrame wsTableFrame;
    boolean doneInit;
    private int fltrField;
    private String fltrStirng;
    private boolean fltrEnabled;
    private int fltrImp;
    private String fltrType;
    private int fltrMinScore;
    private boolean isUpdate;
    private FormFrame addWorkstationForm;

    /**
     * Creates new form WorkstationSCR
     */
    public WorkstationSCR() {
        doneInit = false;
        fltrField = 0;
        fltrStirng = "";
        fltrEnabled = false;
        fltrImp = 0;
        fltrType = "Show All";
        ArrayList<String> wstypes = new ArrayList<String>(PCNMClientStart.cur_ent.getStringWstypes());
        String[] row;
        types = new ArrayList<String[]>();
        for (String typ : wstypes) {
            row = typ.split(",");
            types.add(row);
        }
        initComponents();
        doneInit = true;
    }

    public WorkstationSCR(ArrayList<String> ws_tbl) {
        this();
        doneInit = false;
        this.ws_tbl = ws_tbl;
        rowCounter = ws_tbl.size();
        rowsToShow = new boolean[rowCounter];
        Arrays.fill(rowsToShow, true);
        tableContent = new String[rowCounter][5];
        loadSearchResults();
        tblSearchResault.setEnabled(true);
        wsTableFrame = new FormFrame();
        wsTableFrame.setSize(pnlWorkstationSearchResults.getMinimumSize());
        wsTableFrame.getContentPane().add(pnlWorkstationSearchResults);
        wsTableFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        wsTableFrame.getContentPane().setVisible(true);
        PCNMClientStart.appWindow.setEnabled(false);
        wsTableFrame.setVisible(true);
        doneInit = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWorkstationSearchResults = new javax.swing.JPanel();
        lblResultsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchResault = new javax.swing.JTable();
        lblResultFilterBy = new javax.swing.JLabel();
        btnClose1 = new javax.swing.JButton();
        cmbFltrField = new javax.swing.JComboBox();
        lblFilterStr = new javax.swing.JLabel();
        txtFilterStr = new javax.swing.JTextField();
        lblImportanceFilter = new javax.swing.JLabel();
        lblMinScoreFilter = new javax.swing.JLabel();
        chbEnabledOnly = new javax.swing.JCheckBox();
        lblMinScoreFilter1 = new javax.swing.JLabel();
        cmbFltrImp = new javax.swing.JComboBox();
        cmbFltrType = new javax.swing.JComboBox();
        cmbFltrMinScore = new javax.swing.JComboBox();
        btnNewWorkstation = new javax.swing.JButton();
        pnlAddWorkStationForm = new javax.swing.JPanel();
        lblAddWorkstationTitle = new javax.swing.JLabel();
        lblAddWorkstationName = new javax.swing.JLabel();
        lblAddWorkstationDescription = new javax.swing.JLabel();
        lblAddWorkstationImportance = new javax.swing.JLabel();
        lblAddWorkstationType = new javax.swing.JLabel();
        lblAddWorkstationMinRate = new javax.swing.JLabel();
        lblAddWorkstationStatus = new javax.swing.JLabel();
        txtAddWorkstationMinRate = new javax.swing.JTextField();
        txtAddWorkstationDescription = new javax.swing.JTextField();
        txtAddWorkstationName = new javax.swing.JTextField();
        spnAddWorkstationImportance = new javax.swing.JSpinner();
        cmbAddWorkstationStatus = new javax.swing.JComboBox();
        cmbAddWorkstationType = new javax.swing.JComboBox();
        btnAddWorkstationOK = new javax.swing.JButton();
        btnAddWorkstationCancel = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        lblScreenTitle = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        lblSearchTitle = new javax.swing.JLabel();
        lblSearchName = new javax.swing.JLabel();
        lblSearchDescription = new javax.swing.JLabel();
        lblSearchType = new javax.swing.JLabel();
        lblSearchImportance = new javax.swing.JLabel();
        lblSearchStatus = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox();
        cmbStatus = new javax.swing.JComboBox();
        cmbImportance = new javax.swing.JComboBox();
        btnClose = new javax.swing.JButton();
        lblNoFilter = new javax.swing.JLabel();

        pnlWorkstationSearchResults.setBackground(java.awt.Color.white);

        lblResultsTitle.setBackground(java.awt.Color.white);
        lblResultsTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblResultsTitle.setForeground(java.awt.Color.red);
        lblResultsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultsTitle.setText("Workstations Search Results");

        tblSearchResault.setAutoCreateRowSorter(true);
        tblSearchResault.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblSearchResault.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Description", "Importance", "Status", "Type", "Minimal Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchResault.setRowHeight(32);
        tblSearchResault.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblSearchResault);
        if (tblSearchResault.getColumnModel().getColumnCount() > 0) {
            tblSearchResault.getColumnModel().getColumn(0).setMinWidth(100);
            tblSearchResault.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblSearchResault.getColumnModel().getColumn(1).setMinWidth(100);
            tblSearchResault.getColumnModel().getColumn(1).setPreferredWidth(450);
            tblSearchResault.getColumnModel().getColumn(2).setMinWidth(100);
            tblSearchResault.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblSearchResault.getColumnModel().getColumn(3).setMinWidth(100);
            tblSearchResault.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblSearchResault.getColumnModel().getColumn(4).setMinWidth(100);
            tblSearchResault.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblSearchResault.getColumnModel().getColumn(5).setMinWidth(100);
            tblSearchResault.getColumnModel().getColumn(5).setPreferredWidth(100);
        }
        tblSearchResault.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 24));

        lblResultFilterBy.setBackground(java.awt.Color.white);
        lblResultFilterBy.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblResultFilterBy.setText("Filter By:");

        btnClose1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnClose1.setForeground(java.awt.Color.red);
        btnClose1.setToolTipText("Close screen and return to log-in screen");
        btnClose1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose1.setInheritsPopupMenu(true);
        btnClose1.setLabel("Close");
        btnClose1.setName("btnClose"); // NOI18N
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });

        cmbFltrField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbFltrField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show All", "Workstation Name", "Workstation Description" }));
        cmbFltrField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFltrFieldActionPerformed(evt);
            }
        });

        lblFilterStr.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblFilterStr.setText("Filter String:");

        txtFilterStr.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtFilterStr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFilterStrFocusLost(evt);
            }
        });
        txtFilterStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterStrActionPerformed(evt);
            }
        });

        lblImportanceFilter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblImportanceFilter.setText("Importance Filter:");

        lblMinScoreFilter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMinScoreFilter.setText("Minimal Rate Filter:");

        chbEnabledOnly.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        chbEnabledOnly.setText("Show Enabled Only");
        chbEnabledOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbEnabledOnlyActionPerformed(evt);
            }
        });

        lblMinScoreFilter1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMinScoreFilter1.setText("Workstation Type Filter:");

        cmbFltrImp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbFltrImp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show All", "Greater Then 1", "Less Then 1" }));
        cmbFltrImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFltrImpActionPerformed(evt);
            }
        });

        cmbFltrType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbFltrType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show All" }));
        cmbFltrType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFltrTypeActionPerformed(evt);
            }
        });

        cmbFltrMinScore.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbFltrMinScore.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show All", "Greater Then 100", "Less Then 100" }));
        cmbFltrMinScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFltrMinScoreActionPerformed(evt);
            }
        });

        btnNewWorkstation.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnNewWorkstation.setText("New Workstation");
        btnNewWorkstation.setToolTipText("Add new system user");
        btnNewWorkstation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewWorkstation.setMaximumSize(new java.awt.Dimension(99, 33));
        btnNewWorkstation.setMinimumSize(new java.awt.Dimension(99, 33));
        btnNewWorkstation.setPreferredSize(new java.awt.Dimension(99, 33));
        btnNewWorkstation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewWorkstationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlWorkstationSearchResultsLayout = new javax.swing.GroupLayout(pnlWorkstationSearchResults);
        pnlWorkstationSearchResults.setLayout(pnlWorkstationSearchResultsLayout);
        pnlWorkstationSearchResultsLayout.setHorizontalGroup(
            pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                .addComponent(lblResultsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(291, 291, 291))
            .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                        .addGroup(pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNewWorkstation, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                                .addGroup(pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                                        .addComponent(lblResultFilterBy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbFltrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblFilterStr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFilterStr, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                                        .addComponent(lblImportanceFilter)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbFltrImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(lblMinScoreFilter1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbFltrType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbEnabledOnly)
                                    .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                                        .addComponent(lblMinScoreFilter)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbFltrMinScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlWorkstationSearchResultsLayout.setVerticalGroup(
            pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWorkstationSearchResultsLayout.createSequentialGroup()
                .addComponent(lblResultsTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultFilterBy)
                    .addComponent(cmbFltrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFilterStr)
                    .addComponent(txtFilterStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbEnabledOnly))
                .addGap(18, 18, 18)
                .addGroup(pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImportanceFilter)
                    .addComponent(lblMinScoreFilter)
                    .addComponent(lblMinScoreFilter1)
                    .addComponent(cmbFltrImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFltrType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFltrMinScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlWorkstationSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewWorkstation, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        for (String[] typ : types) {
            cmbFltrType.addItem(typ[1]);
        }

        pnlAddWorkStationForm.setBackground(java.awt.Color.white);
        pnlAddWorkStationForm.setMinimumSize(new java.awt.Dimension(310, 420));

        lblAddWorkstationTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblAddWorkstationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddWorkstationTitle.setText("Add New Workstation");
        lblAddWorkstationTitle.setName("lblAddWorkstationTitle"); // NOI18N

        lblAddWorkstationName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAddWorkstationName.setText("Name:");

        lblAddWorkstationDescription.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAddWorkstationDescription.setText("Description:");

        lblAddWorkstationImportance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAddWorkstationImportance.setText("Importance:");

        lblAddWorkstationType.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAddWorkstationType.setText("Type:");

        lblAddWorkstationMinRate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAddWorkstationMinRate.setText("Minimal Rate:");

        lblAddWorkstationStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAddWorkstationStatus.setText("Status:");

        txtAddWorkstationMinRate.setEditable(false);
        txtAddWorkstationMinRate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAddWorkstationMinRate.setToolTipText("");

        txtAddWorkstationDescription.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAddWorkstationDescription.setToolTipText("");

        txtAddWorkstationName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAddWorkstationName.setToolTipText("");

        spnAddWorkstationImportance.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        spnAddWorkstationImportance.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.1d, 1.9d, 0.1d));

        cmbAddWorkstationStatus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbAddWorkstationStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enabled", "Disabled", "Suspended" }));

        cmbAddWorkstationType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbAddWorkstationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAddWorkstationTypeActionPerformed(evt);
            }
        });

        btnAddWorkstationOK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddWorkstationOK.setText("OK");
        btnAddWorkstationOK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddWorkstationOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkstationOKActionPerformed(evt);
            }
        });

        btnAddWorkstationCancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddWorkstationCancel.setText("Cancel");
        btnAddWorkstationCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddWorkstationCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkstationCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddWorkStationFormLayout = new javax.swing.GroupLayout(pnlAddWorkStationForm);
        pnlAddWorkStationForm.setLayout(pnlAddWorkStationFormLayout);
        pnlAddWorkStationFormLayout.setHorizontalGroup(
            pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddWorkStationFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAddWorkStationFormLayout.createSequentialGroup()
                        .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddWorkstationMinRate)
                            .addComponent(lblAddWorkstationDescription)
                            .addComponent(lblAddWorkstationName)
                            .addComponent(lblAddWorkstationImportance)
                            .addComponent(lblAddWorkstationStatus)
                            .addComponent(lblAddWorkstationType))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAddWorkstationType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAddWorkstationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnAddWorkstationImportance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddWorkstationName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddWorkstationDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddWorkstationMinRate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAddWorkStationFormLayout.createSequentialGroup()
                        .addComponent(btnAddWorkstationOK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddWorkstationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblAddWorkstationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddWorkStationFormLayout.setVerticalGroup(
            pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddWorkStationFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddWorkstationTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddWorkstationName)
                    .addComponent(txtAddWorkstationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddWorkstationDescription)
                    .addComponent(txtAddWorkstationDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddWorkstationImportance)
                    .addComponent(spnAddWorkstationImportance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddWorkstationType)
                    .addComponent(cmbAddWorkstationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddWorkstationMinRate)
                    .addComponent(txtAddWorkstationMinRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddWorkstationStatus)
                    .addComponent(cmbAddWorkstationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddWorkStationFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddWorkstationOK)
                    .addComponent(btnAddWorkstationCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        for (String[] typ : types) {
            cmbAddWorkstationType.addItem(typ[1]);
        }

        setBackground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setToolTipText("Close screen and return to log-in screen");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearch.setInheritsPopupMenu(true);
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblScreenTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblScreenTitle.setForeground(java.awt.Color.red);
        lblScreenTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScreenTitle.setText("Workstations Management");
        lblScreenTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblScreenTitle.setName("lblScreenTitle"); // NOI18N

        btnQuit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQuit.setForeground(java.awt.Color.red);
        btnQuit.setText("Quit");
        btnQuit.setToolTipText("Quit PCNM");
        btnQuit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnQuit.setInheritsPopupMenu(true);
        btnQuit.setName("btnQuit"); // NOI18N
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        lblSearchTitle.setBackground(java.awt.Color.white);
        lblSearchTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblSearchTitle.setForeground(java.awt.Color.red);
        lblSearchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchTitle.setText("Search For Workstations");

        lblSearchName.setBackground(java.awt.Color.white);
        lblSearchName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearchName.setText("Search by Workstation name:");

        lblSearchDescription.setBackground(java.awt.Color.white);
        lblSearchDescription.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearchDescription.setText("Search by Workstation Description:");

        lblSearchType.setBackground(java.awt.Color.white);
        lblSearchType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearchType.setText("Search by Workstation Type:");

        lblSearchImportance.setBackground(java.awt.Color.white);
        lblSearchImportance.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearchImportance.setText("Search by Workstation Importance:");

        lblSearchStatus.setBackground(java.awt.Color.white);
        lblSearchStatus.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSearchStatus.setText("Search by Workstation Status:");

        txtDescription.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        cmbType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Types" }));
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        cmbStatus.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any Status", "Enabled", "Disabled", "Suspended" }));

        cmbImportance.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbImportance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Greater then 1", "Less then 1" }));

        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnClose.setForeground(java.awt.Color.red);
        btnClose.setToolTipText("Close screen and return to log-in screen");
        btnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setInheritsPopupMenu(true);
        btnClose.setLabel("Close");
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblNoFilter.setBackground(java.awt.Color.white);
        lblNoFilter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNoFilter.setForeground(java.awt.Color.red);
        lblNoFilter.setText("Leave text fields empty for all workstations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSearchTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblScreenTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSearchDescription)
                                    .addComponent(lblSearchName)
                                    .addComponent(lblSearchType))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtDescription)
                                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSearchImportance)
                                    .addComponent(lblSearchStatus))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbImportance, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE))
                    .addComponent(lblNoFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScreenTitle)
                .addGap(11, 11, 11)
                .addComponent(lblSearchTitle)
                .addGap(18, 18, 18)
                .addComponent(lblNoFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchType)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchImportance)
                    .addComponent(cmbImportance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSearchStatus)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        for (String[] typ : types) {
            cmbType.addItem(typ[1]);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String name = txtName.getText();
        String description = txtDescription.getText();
        String importance = (String)cmbImportance.getSelectedItem();
        String type = (String)cmbType.getSelectedItem();
        String status = (String)cmbStatus.getSelectedItem();
        try {
            WorkstationCTRL.searchBtnPressed(name, description, importance, type, status);
        } catch (IOException ex) {
           showDialog(this, "Lost Connection with the server", DialogType.ERROR);
            System.exit(0);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        WorkstationCTRL.QuitBtnPressed();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        WorkstationCTRL.closeBtnPressed();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        doneInit = false;
        wsTableFrame.dispose();
        PCNMClientStart.appWindow.setEnabled(true);
        PCNMClientStart.appWindow.requestFocus();
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void txtFilterStrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFilterStrFocusLost
        if (doneInit) {
            fltrStirng = txtFilterStr.getText();
            if (fltrStirng == null) fltrStirng = "";
            applyFilter();
        }
    }//GEN-LAST:event_txtFilterStrFocusLost

    private void txtFilterStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterStrActionPerformed
        if (doneInit) {
            fltrStirng = txtFilterStr.getText();
            if (fltrStirng == null) fltrStirng = "";
            applyFilter();
        }
    }//GEN-LAST:event_txtFilterStrActionPerformed

    private void chbEnabledOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEnabledOnlyActionPerformed
        if (doneInit) {
            fltrEnabled = chbEnabledOnly.isSelected();
            applyFilter();
        }
    }//GEN-LAST:event_chbEnabledOnlyActionPerformed

    private void cmbFltrFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFltrFieldActionPerformed
        if (doneInit) {
            fltrField = cmbFltrField.getSelectedIndex();
            fltrStirng = txtFilterStr.getText();
            if (fltrStirng == null) fltrStirng = "";
            applyFilter();
        }
    }//GEN-LAST:event_cmbFltrFieldActionPerformed

    private void cmbFltrImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFltrImpActionPerformed
        if (doneInit) {
            fltrImp = cmbFltrImp.getSelectedIndex();
            applyFilter();
        }
    }//GEN-LAST:event_cmbFltrImpActionPerformed

    private void cmbFltrTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFltrTypeActionPerformed
        if (doneInit) {
            fltrType = String.valueOf(cmbFltrType.getSelectedItem());
            applyFilter();
        }
    }//GEN-LAST:event_cmbFltrTypeActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void cmbFltrMinScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFltrMinScoreActionPerformed
        if (doneInit) {
            fltrMinScore = cmbFltrMinScore.getSelectedIndex();
            applyFilter();
        }
    }//GEN-LAST:event_cmbFltrMinScoreActionPerformed

    private void btnNewWorkstationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewWorkstationActionPerformed
        isUpdate = false;
        addWorkstationClearFields();
        addWorkstationForm = new FormFrame();
        addWorkstationForm.setSize(pnlAddWorkStationForm.getMinimumSize());
        addWorkstationForm.getContentPane().add(pnlAddWorkStationForm);
        addWorkstationForm.addWindowListener(exitListener);
        addWorkstationForm.getContentPane().setVisible(true);
        wsTableFrame.setEnabled(false);
        addWorkstationForm.setVisible(true);
    }//GEN-LAST:event_btnNewWorkstationActionPerformed

    private void btnAddWorkstationOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkstationOKActionPerformed
        String name = txtAddWorkstationName.getText();
        String description = txtAddWorkstationDescription.getText();
        double importance = (Double)spnAddWorkstationImportance.getValue();
        int type = cmbAddWorkstationType.getSelectedIndex();
        String status = (String)cmbAddWorkstationStatus.getSelectedItem();
        if (name.isEmpty() || description.isEmpty() || type == -1 || status.isEmpty()) {
            showDialog(pnlAddWorkStationForm, "All fields are mandatory.", DialogType.INFO);
            return;
        }
//        if (!isUpdate) {
//            for (int i = 0 ; i < tableContent.length ; i ++) {
//                if (name.equals(tableContent[i][1])) {
//                    showDialog(pnlAddUser, "User type's name must be unique.", DialogType.INFO);
//                    return;
//                }
//            }
//        }
        try {
            if (!WorkstationCTRL.isNameUnique(name)) {
                showDialog(pnlAddWorkStationForm, "Workstation Name must be unique.", DialogType.INFO);
                return;
            }
        } catch (IOException ex) {
            showDialog(pnlAddWorkStationForm, ex.getMessage(), DialogType.ERROR);
            addWorkstationForm.dispose();
            addWorkstationClearFields();
            wsTableFrame.setEnabled(true);
            wsTableFrame.requestFocus();
            return;
        }
        try {
            WorkstationCTRL.AddWorkstationBtnPressed(name, description, importance, status,
                                                    types.get(type)[0], types.get(type)[1], types.get(type)[2], types.get(type)[3], types.get(type)[4]);
        } catch (IOException ex) {
            showDialog(pnlAddWorkStationForm, "Lost Connection with the server", DialogType.ERROR);
            System.exit(0);
        }
        addWorkstationForm.dispose();
        addWorkstationClearFields();
        wsTableFrame.setEnabled(true);
        wsTableFrame.requestFocus();
    }//GEN-LAST:event_btnAddWorkstationOKActionPerformed

    private void btnAddWorkstationCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkstationCancelActionPerformed
        addWorkstationClearFields();
        addWorkstationForm.dispose();
        wsTableFrame.setEnabled(true);
        wsTableFrame.requestFocus();
    }//GEN-LAST:event_btnAddWorkstationCancelActionPerformed

    private void cmbAddWorkstationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAddWorkstationTypeActionPerformed
        int selected = cmbAddWorkstationType.getSelectedIndex();
        if (selected == -1) {
            txtAddWorkstationMinRate.setText("");
            return;
        }
        String[] typ = types.get(selected);
        txtAddWorkstationMinRate.setText(typ[3]);
    }//GEN-LAST:event_cmbAddWorkstationTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWorkstationCancel;
    private javax.swing.JButton btnAddWorkstationOK;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnNewWorkstation;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chbEnabledOnly;
    private javax.swing.JComboBox cmbAddWorkstationStatus;
    private javax.swing.JComboBox cmbAddWorkstationType;
    private javax.swing.JComboBox cmbFltrField;
    private javax.swing.JComboBox cmbFltrImp;
    private javax.swing.JComboBox cmbFltrMinScore;
    private javax.swing.JComboBox cmbFltrType;
    private javax.swing.JComboBox cmbImportance;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddWorkstationDescription;
    private javax.swing.JLabel lblAddWorkstationImportance;
    private javax.swing.JLabel lblAddWorkstationMinRate;
    private javax.swing.JLabel lblAddWorkstationName;
    private javax.swing.JLabel lblAddWorkstationStatus;
    private javax.swing.JLabel lblAddWorkstationTitle;
    private javax.swing.JLabel lblAddWorkstationType;
    private javax.swing.JLabel lblFilterStr;
    private javax.swing.JLabel lblImportanceFilter;
    private javax.swing.JLabel lblMinScoreFilter;
    private javax.swing.JLabel lblMinScoreFilter1;
    private javax.swing.JLabel lblNoFilter;
    private javax.swing.JLabel lblResultFilterBy;
    private javax.swing.JLabel lblResultsTitle;
    private javax.swing.JLabel lblScreenTitle;
    private javax.swing.JLabel lblSearchDescription;
    private javax.swing.JLabel lblSearchImportance;
    private javax.swing.JLabel lblSearchName;
    private javax.swing.JLabel lblSearchStatus;
    private javax.swing.JLabel lblSearchTitle;
    private javax.swing.JLabel lblSearchType;
    private javax.swing.JPanel pnlAddWorkStationForm;
    private javax.swing.JPanel pnlWorkstationSearchResults;
    private javax.swing.JSpinner spnAddWorkstationImportance;
    private javax.swing.JTable tblSearchResault;
    private javax.swing.JTextField txtAddWorkstationDescription;
    private javax.swing.JTextField txtAddWorkstationMinRate;
    private javax.swing.JTextField txtAddWorkstationName;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtFilterStr;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void loadSearchResults() {
        String row;
        DefaultTableModel dtm = (DefaultTableModel)tblSearchResault.getModel();
        dtm.setRowCount(rowCounter);
        int cur_row = 0;
        for (int i = 0 ; i < ws_tbl.size() ; i ++) {
            if (rowsToShow[i]) {
                row = ws_tbl.get(i);
                tableContent[i] = row.split(",");
                dtm.setValueAt(tableContent[i][1], cur_row, 0);
                dtm.setValueAt(tableContent[i][2], cur_row, 1);
                dtm.setValueAt(Double.parseDouble(tableContent[i][3]), cur_row, 2);
                dtm.setValueAt(tableContent[i][4], cur_row, 3);
                dtm.setValueAt(tableContent[i][6], cur_row, 4);
                dtm.setValueAt(Integer.parseInt(tableContent[i][8]), cur_row, 5);
                cur_row ++;
                if (cur_row > rowCounter)
                    i = ws_tbl.size();
            }
        }
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);
        tblSearchResault.getColumnModel().getColumn(2).setCellRenderer(leftRenderer);
        tblSearchResault.getColumnModel().getColumn(5).setCellRenderer(leftRenderer);

    }

    private void applyFilter() {
        Arrays.fill(rowsToShow, true);
        rowCounter = tableContent.length;
        for (int i = 0 ; i < tableContent.length ; i ++) {
            if (rowsToShow[i] && fltrField == 1 && !fltrStirng.isEmpty() && tableContent[i][1].toLowerCase().indexOf(fltrStirng) == -1) rowsToShow[i] = false;
            if (rowsToShow[i] && fltrField == 2 && !fltrStirng.isEmpty() && tableContent[i][2].toLowerCase().indexOf(fltrStirng) == -1) rowsToShow[i] = false;
            if (rowsToShow[i] && fltrImp == 1 && Double.parseDouble(tableContent[i][3]) < 1) rowsToShow[i] = false;
            if (rowsToShow[i] && fltrImp == 2 && Double.parseDouble(tableContent[i][3]) > 1) rowsToShow[i] = false;
            if (rowsToShow[i] && fltrEnabled && !tableContent[i][4].equals("Enabled")) rowsToShow[i] = false;
            if (rowsToShow[i] && !fltrType.equals("Show All") && !tableContent[i][6].equals(fltrType)) rowsToShow[i] = false;
            if (rowsToShow[i] && fltrMinScore == 1 && Integer.parseInt(tableContent[i][8]) < 100) rowsToShow[i] = false;
            if (rowsToShow[i] && fltrMinScore == 2 && Integer.parseInt(tableContent[i][8]) > 100) rowsToShow[i] = false;
            if (!rowsToShow[i]) rowCounter --;
        }
        loadSearchResults();
    }

    private void addWorkstationClearFields() {
        txtAddWorkstationName.setText("");
        txtAddWorkstationDescription.setText("");
        spnAddWorkstationImportance.setValue(new Double(1.0));
        cmbAddWorkstationType.setSelectedIndex(-1);
        cmbAddWorkstationStatus.setSelectedIndex(0);
    }
    
    private WindowListener exitListener = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            addWorkstationClearFields();
            addWorkstationForm.dispose();
            wsTableFrame.setEnabled(true);
            wsTableFrame.requestFocus();
        }
    };
}
